# DeepFashion 实验配置 (ViT-L/14)
setup: ours
experiment: 5.0

# Dataset
dataset_name: deepfashion
num_classes: 23
num_base: 11
num_novel: 12

# Training
seed: 1
batch_size: 256  # ViT-L/14 可以使用更大的batch size

# Text-clustering Method
clustering_method: multi_clip_voting

# Model
# VLMs
model_size: ViT-L/14
#model_size: ViT-L/14@336px

# VQAs
model_size_vqa: FlanT5-XXL

# LLMs
model_type_llm: gpt-3.5-turbo

image_size: 224
# ['RN50@224px', 'RN101@224px', 'RN50x4@288px', 'RN50x16@384px', 'RN50x64@448px',
#  'ViT-B/32@224px', 'ViT-B/16@224px', 'ViT-L/14@224px', 'ViT-L/14@336px']

verbose: False

